baseURL = "/"
languageCode = "it-it"
title = "Psicologa Lecce"
copyright = "PI: 04022480752 - Psicologa Lecce"
theme = 'ananke'


DefaultContentLanguage = "it"
# SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.it]
    title = "Psicologa Lecce"
    weight = 2
    contentDir = "content"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "dark-gray"
  author = "Maria Rosaria Tamborrino"
  description = "Dott.ssa Maria Rosaria Tamborrino - psicologa, psicoterapeuta, EMDR Practitioner. Si occupa di neuropsicologia dell'età evolutiva e adulta e di psicoterapia cognitivo-comportamentale"
  favicon = ""
  site_logo = "logo.png"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-all-site"
  footer_background_color_class = "bg-near-white"
  recent_posts_number = 3
  featured_image = "sfondo_pagina_1.jpg"
  body_classes = "site-body bg-all-site"
  custom_css = ["custom.css"]
  date_format = "02 January 2006"

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 1

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[[params.ananke_socials]]
name = "facebook"
url = "http://www.facebook.com/psicologalecce.tamborrino"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/m.tamborrino.studiointranimam/"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/pub/maria-rosaria-tamborrino/a/718/176"

[[params.ananke_socials]]
name = "envelope"
url = "mailto:mariarosaria.tamborrino@gmail.com"